import type {GetStaticProps} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
    PaymentDetails2,
    StripePaymentMethodCreditCard
} from "../lib/payment-details";

export const getStaticProps: GetStaticProps = async () => {
    const paymentDetails = await PaymentDetails2();

    return {
        props: {
            paymentDetails
        }
    }
}

function CreditCard(paymentDetails: StripePaymentMethodCreditCard) {
    const { id, givenName, familyName } = paymentDetails;
    return (<li key={id}>
        {id}
        <br />
        {givenName} {familyName}
    </li>)
}

function PaymentMethodList(paymentDetails: StripePaymentMethodCreditCard[]) {
    return paymentDetails.map((method: StripePaymentMethodCreditCard) => {
        return CreditCard(method);
    })
}

export default function Home({ paymentDetails }: { paymentDetails: StripePaymentMethodCreditCard[] }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <ul>
                    {PaymentMethodList(paymentDetails)}
                </ul>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
                </a>
            </footer>
        </div>
    )
}
